"""empty message

Revision ID: 00fb105ccbca
Revises: a0e19726d3f8
Create Date: 2020-08-31 03:44:04.109777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fb105ccbca'
down_revision = 'a0e19726d3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingester', sa.Column('option_keywords', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingester', 'option_keywords')
    # ### end Alembic commands ###
