"""empty message

Revision ID: 02efb8965f94
Revises: f7ee457a5838
Create Date: 2020-09-03 08:14:00.367513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02efb8965f94'
down_revision = 'f7ee457a5838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingester', sa.Column('pipeline_name', sa.String(length=255), nullable=True))
    op.drop_column('ingester', 'pipeline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingester', sa.Column('pipeline', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('ingester', 'pipeline_name')
    # ### end Alembic commands ###
