"""empty message

Revision ID: 1049189fa2f3
Revises: 2b6cd532b046
Create Date: 2020-08-28 19:00:28.616598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1049189fa2f3'
down_revision = '2b6cd532b046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor', 'executor_id')
    op.drop_column('executor', 'pipeline_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('pipeline_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('executor', sa.Column('executor_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
