"""empty message

Revision ID: 20200929_084059
Revises: 20200925_023639
Create Date: 2020-09-29 08:40:59.543934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20200929_084059'
down_revision = '20200925_023639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referer', sa.String(length=1023), nullable=True),
    sa.Column('url', sa.String(length=1023), nullable=True),
    sa.Column('url_cache', sa.String(length=1023), nullable=True),
    sa.Column('title', sa.String(length=1023), nullable=True),
    sa.Column('summary', sa.String(length=1023), nullable=True),
    sa.Column('memo', sa.String(length=1023), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_id'), 'topic', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_id'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
