"""empty message

Revision ID: 20201021_001447
Revises: 20201014_191741
Create Date: 2020-10-21 00:14:47.787820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201021_001447'
down_revision = '20201014_191741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('cron', sa.String(length=255), nullable=False),
    sa.Column('broker', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Float(), nullable=True),
    sa.Column('trade_rule', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_trade_job_name')
    )
    op.create_index(op.f('ix_trade_job_id'), 'trade_job', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_job_id'), table_name='trade_job')
    op.drop_table('trade_job')
    # ### end Alembic commands ###
