"""empty message

Revision ID: 20201026_094553
Revises: 20201026_094051
Create Date: 2020-10-26 09:45:54.158725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201026_094553'
down_revision = '20201026_094051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('__crypto_ohlc_daily', 'close_time',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('__crypto_ohlc_daily', 'close_time',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
