"""empty message

Revision ID: 20200929_093643
Revises: 20200929_084536
Create Date: 2020-09-29 09:36:44.075724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20200929_093643'
down_revision = '20200929_084536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__crypto_ohlc_daily', sa.Column('periods', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('__crypto_ohlc_daily', 'periods')
    # ### end Alembic commands ###
