"""empty message

Revision ID: 20200925_023639
Revises: 20200924_104512
Create Date: 2020-09-25 02:36:39.157295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20200925_023639'
down_revision = '20200924_104512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_ohlc_daily', sa.Column('provider', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_ohlc_daily', 'provider')
    # ### end Alembic commands ###
