"""empty message

Revision ID: 20201110_021313
Revises: 20201106_064458
Create Date: 2020-11-10 02:13:14.718672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20201110_021313'
down_revision = '20201106_064458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_trade_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('close_time', sa.Date(), nullable=False),
    sa.Column('size', sa.DECIMAL(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_side', sa.String(length=255), nullable=False),
    sa.Column('entry_price', sa.DECIMAL(), nullable=False),
    sa.Column('entry_commission', sa.DECIMAL(), nullable=False),
    sa.Column('entry_reason', sa.String(length=255), nullable=False),
    sa.Column('settle_date', sa.DateTime(), nullable=False),
    sa.Column('settle_side', sa.String(length=255), nullable=False),
    sa.Column('settle_price', sa.DECIMAL(), nullable=False),
    sa.Column('settle_commission', sa.DECIMAL(), nullable=False),
    sa.Column('settle_reason', sa.String(length=255), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_version', sa.String(length=255), nullable=False),
    sa.Column('is_back_test', sa.Boolean(), nullable=False),
    sa.Column('diff_profit', sa.DECIMAL(), nullable=False),
    sa.Column('diff_profit_rate', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('trade_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trade_state_pkey'),
    comment='注文と状態を管理する。'
    )
    op.drop_table('crypto_trade_results')
    # ### end Alembic commands ###
