"""empty message

Revision ID: 20201110_030403
Revises: 20201110_021709
Create Date: 2020-11-10 03:04:04.011811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201110_030403'
down_revision = '20201110_021709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_trade_results', sa.Column('ask_or_bid', sa.Integer(), nullable=False))
    op.add_column('crypto_trade_results', sa.Column('close_date_interval', sa.Integer(), nullable=False))
    op.add_column('crypto_trade_results', sa.Column('entry_close_date', sa.DateTime(), nullable=False))
    op.add_column('crypto_trade_results', sa.Column('settle_close_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_trade_results', 'settle_close_date')
    op.drop_column('crypto_trade_results', 'entry_close_date')
    op.drop_column('crypto_trade_results', 'close_date_interval')
    op.drop_column('crypto_trade_results', 'ask_or_bid')
    # ### end Alembic commands ###
