"""empty message

Revision ID: 20201110_090851
Revises: 20201110_090058
Create Date: 2020-11-10 09:08:52.216695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201110_090851'
down_revision = '20201110_090058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_job', sa.Column('detector_name', sa.String(length=255), nullable=True))
    op.add_column('trade_job', sa.Column('monitor_topic', sa.String(length=255), nullable=True))
    op.add_column('trade_job', sa.Column('trade_type', sa.String(length=255), nullable=True))
    op.alter_column('trade_job', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('trade_profile', sa.Column('detector_name', sa.String(length=255), nullable=True))
    op.add_column('trade_profile', sa.Column('monitor_topic', sa.String(length=255), nullable=True))
    op.add_column('trade_profile', sa.Column('trade_type', sa.String(length=255), nullable=True))
    op.alter_column('trade_profile', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_profile', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('trade_profile', 'trade_type')
    op.drop_column('trade_profile', 'monitor_topic')
    op.drop_column('trade_profile', 'detector_name')
    op.alter_column('trade_job', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('trade_job', 'trade_type')
    op.drop_column('trade_job', 'monitor_topic')
    op.drop_column('trade_job', 'detector_name')
    # ### end Alembic commands ###
