"""empty message

Revision ID: 20201021_001556
Revises: 20201021_001530
Create Date: 2020-10-21 00:15:57.520730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201021_001556'
down_revision = '20201021_001530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trade_job', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade_job', type_='unique')
    # ### end Alembic commands ###
