"""empty message

Revision ID: 20201022_061055
Revises: 20201021_194126
Create Date: 2020-10-22 06:10:56.512718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201022_061055'
down_revision = '20201021_194126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingester_id', table_name='ingester')
    op.drop_index('ix_ingester_job_id', table_name='ingester_job')
    op.drop_index('ix_ingester_jobgroup_id', table_name='ingester_jobgroup')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_ingester_jobgroup_id', 'ingester_jobgroup', ['id'], unique=False)
    op.create_index('ix_ingester_job_id', 'ingester_job', ['id'], unique=False)
    op.create_index('ix_ingester_id', 'ingester', ['id'], unique=False)
    # ### end Alembic commands ###
