"""empty message

Revision ID: 20200930_201204
Revises: 20200930_064944
Create Date: 2020-09-30 20:12:04.428762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20200930_201204'
down_revision = '20200930_064944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_query', '__crypto_ohlc_daily', ['provider', 'market', 'product', 'periods'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_query', table_name='__crypto_ohlc_daily')
    # ### end Alembic commands ###
