"""empty message

Revision ID: 20200929_084414
Revises: 20200929_084059
Create Date: 2020-09-29 08:44:14.339091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20200929_084414'
down_revision = '20200929_084059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_crypto_ohlc_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_crypto_ohlc_daily_id'), 'store_crypto_ohlc_daily', ['id'], unique=False)
    op.create_table('store_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referer', sa.String(length=1023), nullable=True),
    sa.Column('url', sa.String(length=1023), nullable=True),
    sa.Column('url_cache', sa.String(length=1023), nullable=True),
    sa.Column('title', sa.String(length=1023), nullable=True),
    sa.Column('summary', sa.String(length=1023), nullable=True),
    sa.Column('memo', sa.String(length=1023), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_topic_id'), 'store_topic', ['id'], unique=False)
    op.drop_index('ix_topic_id', table_name='topic')
    op.drop_table('topic')
    op.drop_index('ix_crypto_ohlc_daily_id', table_name='crypto_ohlc_daily')
    op.drop_table('crypto_ohlc_daily')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_ohlc_daily',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('market', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('open_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='crypto_ohlc_daily_pkey')
    )
    op.create_index('ix_crypto_ohlc_daily_id', 'crypto_ohlc_daily', ['id'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referer', sa.VARCHAR(length=1023), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=1023), autoincrement=False, nullable=True),
    sa.Column('url_cache', sa.VARCHAR(length=1023), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1023), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(length=1023), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(length=1023), autoincrement=False, nullable=False),
    sa.Column('detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topic_pkey')
    )
    op.create_index('ix_topic_id', 'topic', ['id'], unique=False)
    op.drop_index(op.f('ix_store_topic_id'), table_name='store_topic')
    op.drop_table('store_topic')
    op.drop_index(op.f('ix_store_crypto_ohlc_daily_id'), table_name='store_crypto_ohlc_daily')
    op.drop_table('store_crypto_ohlc_daily')
    # ### end Alembic commands ###
