"""empty message

Revision ID: 20201110_021709
Revises: 20201110_021313
Create Date: 2020-11-10 02:17:09.980750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201110_021709'
down_revision = '20201110_021313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_trade_results', 'close_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_trade_results', sa.Column('close_time', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
