"""empty message

Revision ID: 20200930_064944
Revises: 20200930_064649
Create Date: 2020-09-30 06:49:45.114853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20200930_064944'
down_revision = '20200930_064649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_price', '__crypto_ohlc_daily', ['provider', 'market', 'product', 'periods', 'close_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_price', '__crypto_ohlc_daily', type_='unique')
    # ### end Alembic commands ###
