"""empty message

Revision ID: 20201028_201320
Revises: 20201026_094553
Create Date: 2020-10-28 20:13:21.163991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201028_201320'
down_revision = '20201026_094553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='検証用に使うテーブル。本番環境では、本テーブルにデータが存在することはありません。'
    )
    op.create_table('trade_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='注文と状態を管理する。'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_state')
    op.drop_table('dummy')
    # ### end Alembic commands ###
