"""empty message

Revision ID: 20201014_190603
Revises: 20201012_182606
Create Date: 2020-10-14 19:06:03.842392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201014_190603'
down_revision = '20201012_182606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_profile', sa.Column('description', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_profile', 'description')
    # ### end Alembic commands ###
