"""empty message

Revision ID: 20201012_182606
Revises: 20200930_201204
Create Date: 2020-10-12 18:26:07.105064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201012_182606'
down_revision = '20200930_201204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('cron', sa.String(length=255), nullable=False),
    sa.Column('broker', sa.String(length=255), nullable=False),
    sa.Column('trade_rule', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uix_name')
    )
    op.create_index(op.f('ix_trade_profile_id'), 'trade_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_profile_id'), table_name='trade_profile')
    op.drop_table('trade_profile')
    # ### end Alembic commands ###
