"""empty message

Revision ID: 20201112_002032
Revises: 20201111_022947
Create Date: 2020-11-12 00:20:33.379502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20201112_002032'
down_revision = '20201111_022947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_job', 'trade_rule')
    op.drop_column('trade_profile', 'trade_rule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_profile', sa.Column('trade_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('trade_job', sa.Column('trade_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
