"""empty message

Revision ID: 20201110_072235
Revises: 20201110_030403
Create Date: 2020-11-10 07:22:36.533300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201110_072235'
down_revision = '20201110_030403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_trade_results', sa.Column('fact_profit', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_trade_results', 'fact_profit')
    # ### end Alembic commands ###
