"""empty message

Revision ID: 20201110_072326
Revises: 20201110_072235
Create Date: 2020-11-10 07:23:27.554149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201110_072326'
down_revision = '20201110_072235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_trade_results', 'fact_profit',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_trade_results', 'fact_profit',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
