"""empty message

Revision ID: 20201021_002002
Revises: 20201021_001556
Create Date: 2020-10-21 00:20:02.555836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201021_002002'
down_revision = '20201021_001556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name', 'trade_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_name', 'trade_profile', ['name'])
    # ### end Alembic commands ###
