"""empty message

Revision ID: 20201021_065048
Revises: 20201021_061544
Create Date: 2020-10-21 06:50:49.175254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201021_065048'
down_revision = '20201021_061544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_job_id', table_name='trade_job')
    op.drop_index('ix_trade_profile_id', table_name='trade_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trade_profile_id', 'trade_profile', ['id'], unique=False)
    op.create_index('ix_trade_job_id', 'trade_job', ['id'], unique=False)
    # ### end Alembic commands ###
