"""empty message

Revision ID: 20200930_032001
Revises: 20200929_093643
Create Date: 2020-09-30 03:20:02.020968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20200930_032001'
down_revision = '20200929_093643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_10', sa.Float(), nullable=False))
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_15', sa.Float(), nullable=False))
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_20', sa.Float(), nullable=False))
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_200', sa.Float(), nullable=False))
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_25', sa.Float(), nullable=False))
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_30', sa.Float(), nullable=False))
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_5', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('__crypto_ohlc_daily', 't_sma_5')
    op.drop_column('__crypto_ohlc_daily', 't_sma_30')
    op.drop_column('__crypto_ohlc_daily', 't_sma_25')
    op.drop_column('__crypto_ohlc_daily', 't_sma_200')
    op.drop_column('__crypto_ohlc_daily', 't_sma_20')
    op.drop_column('__crypto_ohlc_daily', 't_sma_15')
    op.drop_column('__crypto_ohlc_daily', 't_sma_10')
    # ### end Alembic commands ###
