"""empty message

Revision ID: 20201021_003255
Revises: 20201021_002347
Create Date: 2020-10-21 00:32:55.671833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201021_003255'
down_revision = '20201021_002347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trade_profile', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade_profile', type_='unique')
    # ### end Alembic commands ###
