"""empty message

Revision ID: 20201021_001530
Revises: 20201021_001447
Create Date: 2020-10-21 00:15:31.002948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20201021_001530'
down_revision = '20201021_001447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_trade_job_name', 'trade_job', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_trade_job_name', 'trade_job', ['name'])
    # ### end Alembic commands ###
