"""empty message

Revision ID: 2b6cd532b046
Revises: ff19bdf74bf1
Create Date: 2020-08-28 18:58:23.640124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6cd532b046'
down_revision = 'ff19bdf74bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('executor_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('executor_name', sa.String(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executor_id'), 'executor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executor_id'), table_name='executor')
    op.drop_table('executor')
    # ### end Alembic commands ###
