"""empty message

Revision ID: 4188412d11e1
Revises: 22356aca97da
Create Date: 2020-08-28 04:22:03.592259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4188412d11e1'
down_revision = '22356aca97da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=255), nullable=True),
    sa.Column('crawler_name', sa.String(length=255), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('option_keywords', sa.String(length=1023), nullable=True),
    sa.Column('deps', sa.Integer(), nullable=False),
    sa.Column('referer', sa.String(length=1023), nullable=True),
    sa.Column('url', sa.String(length=1023), nullable=True),
    sa.Column('url_cache', sa.String(length=1023), nullable=True),
    sa.Column('title', sa.String(length=1023), nullable=True),
    sa.Column('summary', sa.String(length=1023), nullable=True),
    sa.Column('current_page_num', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_queue_id'), 'index_queue', ['id'], unique=False)
    op.add_column('accounts', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('access_token_secret', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('consumer_key', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('consumer_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'consumer_secret')
    op.drop_column('accounts', 'consumer_key')
    op.drop_column('accounts', 'access_token_secret')
    op.drop_column('accounts', 'access_token')
    op.drop_index(op.f('ix_index_queue_id'), table_name='index_queue')
    op.drop_table('index_queue')
    # ### end Alembic commands ###
