"""empty message

Revision ID: a0e19726d3f8
Revises: ef7fff3b363e
Create Date: 2020-08-31 01:51:03.766081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e19726d3f8'
down_revision = 'ef7fff3b363e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingester', 'option_keywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingester', sa.Column('option_keywords', sa.VARCHAR(length=1023), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
