"""empty message

Revision ID: a0e32b898309
Revises: ae3b2929b97f
Create Date: 2020-07-02 11:11:13.720143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e32b898309'
down_revision = 'ae3b2929b97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_test')
    # ### end Alembic commands ###
