"""empty message

Revision ID: d20ccc000106
Revises: a17fdc9fc42f
Create Date: 2020-09-02 10:17:00.142633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20ccc000106'
down_revision = 'a17fdc9fc42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_email', table_name='accounts')
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_index('ix_accounts_username', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lock', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consumer_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consumer_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey')
    )
    op.create_index('ix_accounts_username', 'accounts', ['username'], unique=True)
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    op.create_index('ix_accounts_email', 'accounts', ['email'], unique=True)
    # ### end Alembic commands ###
