"""empty message

Revision ID: ef7fff3b363e
Revises: 1e2869a009a1
Create Date: 2020-08-30 12:35:24.252648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7fff3b363e'
down_revision = '1e2869a009a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingester', 'option_keywords',
               existing_type=sa.VARCHAR(length=1023),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingester', 'option_keywords',
               existing_type=sa.VARCHAR(length=1023),
               nullable=True)
    # ### end Alembic commands ###
