"""empty message

Revision ID: f7ee457a5838
Revises: d20ccc000106
Create Date: 2020-09-03 06:05:17.212054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ee457a5838'
down_revision = 'd20ccc000106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=255), nullable=True),
    sa.Column('crawler_name', sa.String(length=255), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('option_keywords', sa.JSON(), nullable=False),
    sa.Column('deps', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executor_job_id'), 'executor_job', ['id'], unique=False)
    op.create_table('ingester_jobgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=1023), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingester_jobgroup_id'), 'ingester_jobgroup', ['id'], unique=False)
    op.create_table('ingester_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1023), nullable=False),
    sa.Column('pipeline_name', sa.String(length=255), nullable=True),
    sa.Column('crawler_name', sa.String(length=255), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('option_keywords', sa.JSON(), nullable=False),
    sa.Column('deps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ingester_jobgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingester_job_id'), 'ingester_job', ['id'], unique=False)
    op.add_column('ingester', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingester', 'ingester_job', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingester', type_='foreignkey')
    op.drop_column('ingester', 'parent_id')
    op.drop_index(op.f('ix_ingester_job_id'), table_name='ingester_job')
    op.drop_table('ingester_job')
    op.drop_index(op.f('ix_ingester_jobgroup_id'), table_name='ingester_jobgroup')
    op.drop_table('ingester_jobgroup')
    op.drop_index(op.f('ix_executor_job_id'), table_name='executor_job')
    op.drop_table('executor_job')
    # ### end Alembic commands ###
