"""empty message

Revision ID: ff19bdf74bf1
Revises: 71efd80bab8b
Create Date: 2020-08-28 08:21:49.977251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff19bdf74bf1'
down_revision = '71efd80bab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_queue', sa.Column('detail', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_queue', 'detail')
    # ### end Alembic commands ###
