version: '3'
services:
  # selenium:
  #  image: selenium/standalone-chrome
  selenium-debug:
    # 処理過程をデバッグしたい場合に利用(VNC portでリモート接続可能)
    # image: selenium/standalone-chrome-debug
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
    # environment:
      # - IS_WORKER=0
      # - START_XVFB: false # ヘッドレスモード 画面描画なしで利用する場合は、web driverはヘッドレスモードで実行しないといけない
      # - VNC_NO_PASSWORD=1 # VNC接続時認証なし
      # - GRID_DEBUG: true # 出力されるログの量が増える？
    volumes:
      - ./backend/app:/app:rw
      - /dev/shm:/dev/shm # TODO: 意味をよく理解する。
    ports:
      - "5900:5900" # VNC　defualtはsecretでログイン
      - "80:80"
      - "8080:8080"
      - "2222:22" # SSH

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  # queue port
      - 15672:15672  #rabbitmq management console guest:guest
  # sudo apt install rabbitmq-server

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
#    deploy:
#      placement:
#        constraints:
#          - node.labels.${STACK_NAME?Variable not set}.app-db-data == true

  pdadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env
    ports:
    - "5050:5050"

volumes:
  app-db-data:

